src/TuckShop/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TuckShop.Models
{
    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string CellPhoneNumber { get; set; }
        public string Role { get; set; }
        public List<Order> orders { get; set; }
    }
}

src/TuckShop/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using TuckShop.Models;
using System.Threading;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using TuckShop.BusinessLogic;
using Microsoft.Extensions.Logging;

namespace TuckShop.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private Model _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger _logger;
        public UserController(ILoggerFactory loggerFactory, Model context, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _logger = loggerFactory.CreateLogger<UserController>();
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }
        public IActionResult Index()
        {
           var claim =  _signInManager.IsSignedIn(User);
            return View();
        }
        [HttpPost]
        public IActionResult AllProducts()
        {
            var model = _context.Products.ToList();
            var drinks = model.Where(w => w.Category == "Drinks").ToList();
            var food = model.Where(w => w.Category == "Food").ToList();
            var sweets = model.Where(w => w.Category == "Sweets").ToList();
            return Json(new { Drinks = drinks, Food = food, Sweets = sweets, success = true });
        }

        [HttpPost]
        public IActionResult ByCategory(string id)
        {
            var model = _context.Products.Where(w => w.Category == id).ToList();
            return Json(new { list = model, success = true });
        }
        [HttpPost]
        public IActionResult PlaceOrder(List<OrderInputModel> list)
        {
            var user = new User();
            if (_context.Users.Any(a => a.Email == User.Identities.First().Name))
            {
                user = _context.Users.Where(w => w.Email == User.Identities.First().Name).First();
            }
            ProcessOrder processOrder = new ProcessOrder();
            var response = processOrder.processOrderTask(list,user);
            var order = response.order;
            if (_context.Orders.Any())
            {
                var previousRef = _context.Orders.First().Id;
                order.Reference = (previousRef + 1).ToString();
            }else
            {
                order.Reference = 1.ToString();
            }
            try
            {
                _context.Orders.Add(order);
                foreach (var item in response.lineItems)
                {
                    item.OrderId = order.Id;
                    _context.LineItems.Add(item);
                }
            }catch(Exception ex)
            {
                _logger.LogError("Failed to map LineItems and Order, check ProcessOrder Class.");
            }
            try
            {
                _context.SaveChanges();
            }catch(Exception ex)
            {
                _logger.LogError("Failed to save Order.");
            }
            finally
            {
                _context.Dispose();
            }
                    
            return Json(new { success = true, message = "Your Order has been submitted." });
        }
    }
}

src/TuckShop/Views/User/Index.cshtml
<div class="col-lg-12">
    <br />
</div>

<div class="jumbotron container">
    <h1>Shop</h1>
    <p>
        Get all the snacks you need.
    </p>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-3 col-md-offset-1">
            <div class="box text-center" id="DrinksBox">
                <span class="text-center" id="drinksContent">
                    Drinks
                </span>
            </div>
        </div>
        <div class="col-md-3">
            <div class="box text-center"  id="FoodBox">
                <span class="text-center" id="foodContent">
                    Food
                </span>
            </div>
        </div>
        <div class="col-md-3">
            <div class="box text-center" id="SweetsBox">
                <span class="text-center" id="sweetsContent">
                    Sweets
                </span>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <br />
            <br />
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Order</h3>
                </div>
                <div class="panel-body">
                    <div class="list-group" id="">
                        <div class='col-sm-6'>
                            <a href='#' id="" class='list-group-item' active>Item Name</a>
                        </div>
                        <div class='col-sm-6'>
                            <a href='#' class='list-group-item'>Price</a>
                        </div>
                        <div id="orderContent">

                        </div>
                       
                    </div>
                    <div class="col-md-12"><br /><br /></div>
                    <input type="submit" class="btn btn-success" value="Submit" id="submitOrder" />
                </div>
            </div>
        </div>
    </div>
</div>

    <script type="text/javascript">
        $(document).ready(function () {
            var drinksList = [];
            var foodList = [];
            var sweetsList = [];
            $.post('@(Url.Action("AllProducts","User"))', "", function (data, status) {
                drinksList = data.drinks;
                foodList = data.food;
                sweetsList = data.sweets;
            });
            state = {
                Drinks: false,
                Food: false,
                Sweets: false
            };
            $(document).on('click', '#DrinksBox', function () {
                OrderModule.showDrinks(state,drinksList);
               
            });
            $(document).on('click', '#FoodBox', function () {
                OrderModule.showFood(state, foodList);
            });
            $(document).on('click', '#SweetsBox', function () {
                OrderModule.showSweets(state, sweetsList);
            });
            $(document).on('click', '.selectItem', function () {
                let id = $(this).data("id");
                let value = $(this).data("val");
                let price = $(this).data("price");
                OrderModule.createOrder(value, id, price);
            });
            $(document).on('click', '#submitOrder', function () {
                let list = [];
                var product = {
                    Count: "",
                    ProductId:""
                };
                $.each(OrderModule.order, function (index,value) {
                    $.each
                 });

            });
        });
    </script>